<?php

namespace Database\Seeders\Install;

/**
 * Reference data for the gateways table, generated from install/database.sql.
 *
 * Primary keys are written explicitly because other seeded tables reference them by id.
 */
class GatewaysSeeder extends InstallSeeder
{
    public function run(): void
    {
        $this->insertRows('gateways', [
            ['id' => '1', 'form_id' => '0', 'code' => '101', 'name' => 'Paypal - Basic', 'alias' => 'Paypal', 'image' => '66f93024b850f1727606820.png', 'status' => '1', 'gateway_parameters' => '{"paypal_email":{"title":"PayPal Email","global":true,"value":"sb-sie1e33346198@business.example.com"}}', 'supported_currencies' => '{"AUD":"AUD","BRL":"BRL","CAD":"CAD","CZK":"CZK","DKK":"DKK","EUR":"EUR","HKD":"HKD","HUF":"HUF","INR":"INR","ILS":"ILS","JPY":"JPY","MYR":"MYR","MXN":"MXN","TWD":"TWD","NZD":"NZD","NOK":"NOK","PHP":"PHP","PLN":"PLN","GBP":"GBP","RUB":"RUB","SGD":"SGD","SEK":"SEK","CHF":"CHF","THB":"THB","USD":"$"}', 'crypto' => '0', 'extra' => null, 'description' => null, 'created_at' => '2019-09-14 13:14:22', 'updated_at' => '2024-10-13 03:59:25'],
            ['id' => '2', 'form_id' => '0', 'code' => '102', 'name' => 'PerfectMoney', 'alias' => 'PerfectMoney', 'image' => '66f9305b163861727606875.png', 'status' => '1', 'gateway_parameters' => '{"passphrase":{"title":"ALTERNATE PASSPHRASE","global":true,"value":"h9Rz18d60KeErSFPUViTlTyUX"},"wallet_id":{"title":"PM Wallet","global":false,"value":""}}', 'supported_currencies' => '{"USD":"$","EUR":"\\u20ac"}', 'crypto' => '0', 'extra' => null, 'description' => null, 'created_at' => '2019-09-14 13:14:22', 'updated_at' => '2024-10-13 05:05:22'],
            ['id' => '3', 'form_id' => '0', 'code' => '103', 'name' => 'Stripe - Hosted', 'alias' => 'Stripe', 'image' => '66f932d3898531727607507.png', 'status' => '1', 'gateway_parameters' => '{"secret_key":{"title":"Secret Key","global":true,"value":"sk_test_51Q6RC200ViU9uYNAreOGXIikLFE4VKrRNw92sFrDgqv1mMS7HKsrDsTOd9g6ug6mWVnhQGhAlfzwkzivhLgQJGWR00cmSSbqtf"},"publishable_key":{"title":"PUBLISHABLE KEY","global":true,"value":"pk_test_51Q6RC200ViU9uYNAdEkyqVKhIzbLzJci72Or96xppTkZgDkzOjRiZC6Pz6Nol5FqUraLUnu9Ug0Zt8K5TXrJ1g8H00qMlrHnMl"}}', 'supported_currencies' => '{"USD":"USD","AUD":"AUD","BRL":"BRL","CAD":"CAD","CHF":"CHF","DKK":"DKK","EUR":"EUR","GBP":"GBP","HKD":"HKD","INR":"INR","JPY":"JPY","MXN":"MXN","MYR":"MYR","NOK":"NOK","NZD":"NZD","PLN":"PLN","SEK":"SEK","SGD":"SGD"}', 'crypto' => '0', 'extra' => null, 'description' => null, 'created_at' => '2019-09-14 13:14:22', 'updated_at' => '2024-10-05 00:27:02'],
            ['id' => '5', 'form_id' => '0', 'code' => '105', 'name' => 'PayTM', 'alias' => 'Paytm', 'image' => '66f9305278b331727606866.png', 'status' => '1', 'gateway_parameters' => '{"MID":{"title":"Merchant ID","global":true,"value":"-----------"},"merchant_key":{"title":"Merchant Key","global":true,"value":"-----------"},"WEBSITE":{"title":"Paytm Website","global":true,"value":"-----------"},"INDUSTRY_TYPE_ID":{"title":"Industry Type","global":true,"value":"-----------"},"CHANNEL_ID":{"title":"CHANNEL ID","global":true,"value":"-----------"},"transaction_url":{"title":"Transaction URL","global":true,"value":"-----------"},"transaction_status_url":{"title":"Transaction STATUS URL","global":true,"value":"-----------"}}', 'supported_currencies' => '{"AUD":"AUD","ARS":"ARS","BDT":"BDT","BRL":"BRL","BGN":"BGN","CAD":"CAD","CLP":"CLP","CNY":"CNY","COP":"COP","HRK":"HRK","CZK":"CZK","DKK":"DKK","EGP":"EGP","EUR":"EUR","GEL":"GEL","GHS":"GHS","HKD":"HKD","HUF":"HUF","INR":"INR","IDR":"IDR","ILS":"ILS","JPY":"JPY","KES":"KES","MYR":"MYR","MXN":"MXN","MAD":"MAD","NPR":"NPR","NZD":"NZD","NGN":"NGN","NOK":"NOK","PKR":"PKR","PEN":"PEN","PHP":"PHP","PLN":"PLN","RON":"RON","RUB":"RUB","SGD":"SGD","ZAR":"ZAR","KRW":"KRW","LKR":"LKR","SEK":"SEK","CHF":"CHF","THB":"THB","TRY":"TRY","UGX":"UGX","UAH":"UAH","AED":"AED","GBP":"GBP","USD":"USD","VND":"VND","XOF":"XOF"}', 'crypto' => '0', 'extra' => null, 'description' => null, 'created_at' => '2019-09-14 13:14:22', 'updated_at' => '2024-10-14 00:19:59'],
            ['id' => '6', 'form_id' => '0', 'code' => '106', 'name' => 'Payeer', 'alias' => 'Payeer', 'image' => '66f93018e4b7c1727606808.png', 'status' => '1', 'gateway_parameters' => '{"merchant_id":{"title":"Merchant ID","global":true,"value":"P1124379867"},"secret_key":{"title":"Secret key","global":true,"value":"768336"}}', 'supported_currencies' => '{"USD":"USD","EUR":"EUR","RUB":"RUB"}', 'crypto' => '0', 'extra' => '{"status":{"title": "Status URL","value":"ipn.Payeer"}}', 'description' => null, 'created_at' => '2019-09-14 13:14:22', 'updated_at' => '2024-10-13 03:41:46'],
            ['id' => '7', 'form_id' => '0', 'code' => '107', 'name' => 'PayStack', 'alias' => 'Paystack', 'image' => '66f9303d3ca031727606845.png', 'status' => '1', 'gateway_parameters' => '{"public_key":{"title":"Public key","global":true,"value":"pk_test_7a71410e62ae07cad950d94e4a3827b974937450"},"secret_key":{"title":"Secret key","global":true,"value":"sk_test_e8cf00c8c7fc173b60f02199e2752e2f34e50494"}}', 'supported_currencies' => '{"USD":"USD","NGN":"NGN"}', 'crypto' => '0', 'extra' => '{"callback":{"title": "Callback URL","value":"ipn.Paystack"},"webhook":{"title": "Webhook URL","value":"ipn.Paystack"}}
', 'description' => null, 'created_at' => '2019-09-14 13:14:22', 'updated_at' => '2024-10-13 04:19:28'],
            ['id' => '9', 'form_id' => '0', 'code' => '109', 'name' => 'Flutterwave', 'alias' => 'Flutterwave', 'image' => '66f92fb282a3a1727606706.png', 'status' => '1', 'gateway_parameters' => '{"public_key":{"title":"Public Key","global":true,"value":"FLWPUBK_TEST-0ee1835b2e1088d2a529356ec7dcdb30-X"},"secret_key":{"title":"Secret Key","global":true,"value":"FLWSECK_TEST-6c5417024ef775a0eabfb021d41369f8-X"},"encryption_key":{"title":"Encryption Key","global":true,"value":"FLWSECK_TEST78b28d6fdf42"}}', 'supported_currencies' => '{"BIF":"BIF","CAD":"CAD","CDF":"CDF","CVE":"CVE","EUR":"EUR","GBP":"GBP","GHS":"GHS","GMD":"GMD","GNF":"GNF","KES":"KES","LRD":"LRD","MWK":"MWK","MZN":"MZN","NGN":"NGN","RWF":"RWF","SLL":"SLL","STD":"STD","TZS":"TZS","UGX":"UGX","USD":"USD","XAF":"XAF","XOF":"XOF","ZMK":"ZMK","ZMW":"ZMW","ZWD":"ZWD"}', 'crypto' => '0', 'extra' => null, 'description' => null, 'created_at' => '2019-09-14 13:14:22', 'updated_at' => '2024-10-13 01:33:13'],
            ['id' => '10', 'form_id' => '0', 'code' => '110', 'name' => 'RazorPay', 'alias' => 'Razorpay', 'image' => '66f93067ae7661727606887.png', 'status' => '1', 'gateway_parameters' => '{"key_id":{"title":"Key Id","global":true,"value":"-------------"},"key_secret":{"title":"Key Secret ","global":true,"value":"------------"}}', 'supported_currencies' => '{"INR":"INR"}', 'crypto' => '0', 'extra' => null, 'description' => null, 'created_at' => '2019-09-14 13:14:22', 'updated_at' => '2024-10-14 00:20:13'],
            ['id' => '12', 'form_id' => '0', 'code' => '112', 'name' => 'Instamojo', 'alias' => 'Instamojo', 'image' => '66f92fbe2ccbb1727606718.png', 'status' => '1', 'gateway_parameters' => '{"api_key":{"title":"API KEY","global":true,"value":"--------------"},"auth_token":{"title":"Auth Token","global":true,"value":"----------------"},"salt":{"title":"Salt","global":true,"value":"------------"}}', 'supported_currencies' => '{"INR":"INR"}', 'crypto' => '0', 'extra' => null, 'description' => null, 'created_at' => '2019-09-14 13:14:22', 'updated_at' => '2024-10-14 00:19:23'],
            ['id' => '15', 'form_id' => '0', 'code' => '503', 'name' => 'CoinPayments Crypto', 'alias' => 'Coinpayments', 'image' => '66f92f90365d41727606672.png', 'status' => '1', 'gateway_parameters' => '{"public_key":{"title":"Public Key","global":true,"value":"222a8c8825477fbea80812a9d5d70057e4821e43198926daa075fdc08cc98cd6"},"private_key":{"title":"Private Key","global":true,"value":"6d049b6B91a5eBe2053bb21eAa0DCb60f33790ec96B2342192804b0e9dfFf741"},"merchant_id":{"title":"Merchant ID","global":true,"value":"47818ed2d6962bcab1eba829e38ad0c4"}}', 'supported_currencies' => '{"BTC":"Bitcoin","BTC.LN":"Bitcoin (Lightning Network)","LTC":"Litecoin","CPS":"CPS Coin","VLX":"Velas","APL":"Apollo","AYA":"Aryacoin","BAD":"Badcoin","BCD":"Bitcoin Diamond","BCH":"Bitcoin Cash","BCN":"Bytecoin","BEAM":"BEAM","BITB":"Bean Cash","BLK":"BlackCoin","BSV":"Bitcoin SV","BTAD":"Bitcoin Adult","BTG":"Bitcoin Gold","BTT":"BitTorrent","CLOAK":"CloakCoin","CLUB":"ClubCoin","CRW":"Crown","CRYP":"CrypticCoin","CRYT":"CryTrExCoin","CURE":"CureCoin","DASH":"DASH","DCR":"Decred","DEV":"DeviantCoin","DGB":"DigiByte","DOGE":"Dogecoin","EBST":"eBoost","EOS":"EOS","ETC":"Ether Classic","ETH":"Ethereum","ETN":"Electroneum","EUNO":"EUNO","EXP":"EXP","Expanse":"Expanse","FLASH":"FLASH","GAME":"GameCredits","GLC":"Goldcoin","GRS":"Groestlcoin","KMD":"Komodo","LOKI":"LOKI","LSK":"LSK","MAID":"MaidSafeCoin","MUE":"MonetaryUnit","NAV":"NAV Coin","NEO":"NEO","NMC":"Namecoin","NVST":"NVO Token","NXT":"NXT","OMNI":"OMNI","PINK":"PinkCoin","PIVX":"PIVX","POT":"PotCoin","PPC":"Peercoin","PROC":"ProCurrency","PURA":"PURA","QTUM":"QTUM","RES":"Resistance","RVN":"Ravencoin","RVR":"RevolutionVR","SBD":"Steem Dollars","SMART":"SmartCash","SOXAX":"SOXAX","STEEM":"STEEM","STRAT":"STRAT","SYS":"Syscoin","TPAY":"TokenPay","TRIGGERS":"Triggers","TRX":" TRON","UBQ":"Ubiq","UNIT":"UniversalCurrency","USDT":"Tether USD (Omni Layer)","USDT.BEP20":"Tether USD (BSC Chain)","USDT.ERC20":"Tether USD (ERC20)","USDT.TRC20":"Tether USD (Tron/TRC20)","VTC":"Vertcoin","WAVES":"Waves","XCP":"Counterparty","XEM":"NEM","XMR":"Monero","XSN":"Stakenet","XSR":"SucreCoin","XVG":"VERGE","XZC":"ZCoin","ZEC":"ZCash","ZEN":"Horizen"}', 'crypto' => '1', 'extra' => null, 'description' => null, 'created_at' => '2019-09-14 13:14:22', 'updated_at' => '2024-10-13 06:14:28'],
            ['id' => '16', 'form_id' => '0', 'code' => '504', 'name' => 'CoinPayments Fiat', 'alias' => 'CoinpaymentsFiat', 'image' => '66f92fa7d56851727606695.png', 'status' => '1', 'gateway_parameters' => '{"merchant_id":{"title":"Merchant ID","global":true,"value":"6515561"}}', 'supported_currencies' => '{"USD":"USD","AUD":"AUD","BRL":"BRL","CAD":"CAD","CHF":"CHF","CLP":"CLP","CNY":"CNY","DKK":"DKK","EUR":"EUR","GBP":"GBP","HKD":"HKD","INR":"INR","ISK":"ISK","JPY":"JPY","KRW":"KRW","NZD":"NZD","PLN":"PLN","RUB":"RUB","SEK":"SEK","SGD":"SGD","THB":"THB","TWD":"TWD"}', 'crypto' => '0', 'extra' => null, 'description' => null, 'created_at' => '2019-09-14 13:14:22', 'updated_at' => '2024-09-29 04:44:55'],
            ['id' => '17', 'form_id' => '0', 'code' => '505', 'name' => 'Coingate', 'alias' => 'Coingate', 'image' => '66f92f1dafc6e1727606557.png', 'status' => '1', 'gateway_parameters' => '{"api_key":{"title":"API Key","global":true,"value":"------------------"}}', 'supported_currencies' => '{"USD":"USD","EUR":"EUR"}', 'crypto' => '0', 'extra' => null, 'description' => null, 'created_at' => '2019-09-14 13:14:22', 'updated_at' => '2024-10-14 00:19:09'],
            ['id' => '18', 'form_id' => '0', 'code' => '506', 'name' => 'CoinbaseCommerce', 'alias' => 'CoinbaseCommerce', 'image' => '66f92e80485251727606400.png', 'status' => '1', 'gateway_parameters' => '{"api_key":{"title":"API Key","global":true,"value":"------------------"},"secret":{"title":"Webhook Shared Secret","global":true,"value":"-------------"}}', 'supported_currencies' => '{"USD":"USD","EUR":"EUR","JPY":"JPY","GBP":"GBP","AUD":"AUD","CAD":"CAD","CHF":"CHF","CNY":"CNY","SEK":"SEK","NZD":"NZD","MXN":"MXN","SGD":"SGD","HKD":"HKD","NOK":"NOK","KRW":"KRW","TRY":"TRY","RUB":"RUB","INR":"INR","BRL":"BRL","ZAR":"ZAR","AED":"AED","AFN":"AFN","ALL":"ALL","AMD":"AMD","ANG":"ANG","AOA":"AOA","ARS":"ARS","AWG":"AWG","AZN":"AZN","BAM":"BAM","BBD":"BBD","BDT":"BDT","BGN":"BGN","BHD":"BHD","BIF":"BIF","BMD":"BMD","BND":"BND","BOB":"BOB","BSD":"BSD","BTN":"BTN","BWP":"BWP","BYN":"BYN","BZD":"BZD","CDF":"CDF","CLF":"CLF","CLP":"CLP","COP":"COP","CRC":"CRC","CUC":"CUC","CUP":"CUP","CVE":"CVE","CZK":"CZK","DJF":"DJF","DKK":"DKK","DOP":"DOP","DZD":"DZD","EGP":"EGP","ERN":"ERN","ETB":"ETB","FJD":"FJD","FKP":"FKP","GEL":"GEL","GGP":"GGP","GHS":"GHS","GIP":"GIP","GMD":"GMD","GNF":"GNF","GTQ":"GTQ","GYD":"GYD","HNL":"HNL","HRK":"HRK","HTG":"HTG","HUF":"HUF","IDR":"IDR","ILS":"ILS","IMP":"IMP","IQD":"IQD","IRR":"IRR","ISK":"ISK","JEP":"JEP","JMD":"JMD","JOD":"JOD","KES":"KES","KGS":"KGS","KHR":"KHR","KMF":"KMF","KPW":"KPW","KWD":"KWD","KYD":"KYD","KZT":"KZT","LAK":"LAK","LBP":"LBP","LKR":"LKR","LRD":"LRD","LSL":"LSL","LYD":"LYD","MAD":"MAD","MDL":"MDL","MGA":"MGA","MKD":"MKD","MMK":"MMK","MNT":"MNT","MOP":"MOP","MRO":"MRO","MUR":"MUR","MVR":"MVR","MWK":"MWK","MYR":"MYR","MZN":"MZN","NAD":"NAD","NGN":"NGN","NIO":"NIO","NPR":"NPR","OMR":"OMR","PAB":"PAB","PEN":"PEN","PGK":"PGK","PHP":"PHP","PKR":"PKR","PLN":"PLN","PYG":"PYG","QAR":"QAR","RON":"RON","RSD":"RSD","RWF":"RWF","SAR":"SAR","SBD":"SBD","SCR":"SCR","SDG":"SDG","SHP":"SHP","SLL":"SLL","SOS":"SOS","SRD":"SRD","SSP":"SSP","STD":"STD","SVC":"SVC","SYP":"SYP","SZL":"SZL","THB":"THB","TJS":"TJS","TMT":"TMT","TND":"TND","TOP":"TOP","TTD":"TTD","TWD":"TWD","TZS":"TZS","UAH":"UAH","UGX":"UGX","UYU":"UYU","UZS":"UZS","VEF":"VEF","VND":"VND","VUV":"VUV","WST":"WST","XAF":"XAF","XAG":"XAG","XAU":"XAU","XCD":"XCD","XDR":"XDR","XOF":"XOF","XPD":"XPD","XPF":"XPF","XPT":"XPT","YER":"YER","ZMW":"ZMW","ZWL":"ZWL"}

', 'crypto' => '0', 'extra' => '{"endpoint":{"title": "Webhook Endpoint","value":"ipn.CoinbaseCommerce"}}', 'description' => null, 'created_at' => '2019-09-14 13:14:22', 'updated_at' => '2024-10-14 00:18:55'],
            ['id' => '24', 'form_id' => '0', 'code' => '113', 'name' => 'Paypal - Express', 'alias' => 'PaypalSdk', 'image' => '66f954f3b28261727616243.png', 'status' => '1', 'gateway_parameters' => '{"clientId":{"title":"Paypal Client ID","global":true,"value":"AYq9c_gjnfFiLpWdotm-5XTw-RwtWtBrxIEW7IJGcjmq6cLDcTOjSSVlIqnIq4dYWnxrOEeK7s0UuuCy"},"clientSecret":{"title":"Client Secret","global":true,"value":"ECXn_0gIPEdgVDiPfh-zR3KFm5WfmZe5UvhDrKNNa59i5bTSZ3K4S9QFb9uJNZ-vjBGEwcdKD0SRQsP5"}}', 'supported_currencies' => '{"AUD":"AUD","BRL":"BRL","CAD":"CAD","CZK":"CZK","DKK":"DKK","EUR":"EUR","HKD":"HKD","HUF":"HUF","INR":"INR","ILS":"ILS","JPY":"JPY","MYR":"MYR","MXN":"MXN","TWD":"TWD","NZD":"NZD","NOK":"NOK","PHP":"PHP","PLN":"PLN","GBP":"GBP","RUB":"RUB","SGD":"SGD","SEK":"SEK","CHF":"CHF","THB":"THB","USD":"$"}', 'crypto' => '0', 'extra' => null, 'description' => null, 'created_at' => '2019-09-14 13:14:22', 'updated_at' => '2024-10-13 03:59:51'],
            ['id' => '25', 'form_id' => '0', 'code' => '114', 'name' => 'Stripe - Checkout', 'alias' => 'StripeV3', 'image' => '66f930941abc51727606932.png', 'status' => '1', 'gateway_parameters' => '{"secret_key":{"title":"Secret Key","global":true,"value":"sk_test_51Q6RC200ViU9uYNAreOGXIikLFE4VKrRNw92sFrDgqv1mMS7HKsrDsTOd9g6ug6mWVnhQGhAlfzwkzivhLgQJGWR00cmSSbqtf"},"publishable_key":{"title":"PUBLISHABLE KEY","global":true,"value":"pk_test_51Q6RC200ViU9uYNAdEkyqVKhIzbLzJci72Or96xppTkZgDkzOjRiZC6Pz6Nol5FqUraLUnu9Ug0Zt8K5TXrJ1g8H00qMlrHnMl"},"end_point":{"title":"End Point Secret","global":true,"value":"whsec_VnTLcUcx5bMenhc6P0PZiTR0T6NGs5yF"}}', 'supported_currencies' => '{"USD":"USD","AUD":"AUD","BRL":"BRL","CAD":"CAD","CHF":"CHF","DKK":"DKK","EUR":"EUR","GBP":"GBP","HKD":"HKD","INR":"INR","JPY":"JPY","MXN":"MXN","MYR":"MYR","NOK":"NOK","NZD":"NZD","PLN":"PLN","SEK":"SEK","SGD":"SGD"}', 'crypto' => '0', 'extra' => '{"webhook":{"title": "Webhook Endpoint","value":"ipn.StripeV3"}}', 'description' => null, 'created_at' => '2019-09-14 13:14:22', 'updated_at' => '2024-10-05 00:25:34'],
            ['id' => '36', 'form_id' => '0', 'code' => '119', 'name' => 'MercadoPago', 'alias' => 'MercadoPago', 'image' => '66f92fcac0e111727606730.png', 'status' => '1', 'gateway_parameters' => '{"access_token":{"title":"Access Token","global":true,"value":"--------------"}}', 'supported_currencies' => '{"USD":"USD","CAD":"CAD","CHF":"CHF","DKK":"DKK","EUR":"EUR","GBP":"GBP","NOK":"NOK","PLN":"PLN","SEK":"SEK","AUD":"AUD","NZD":"NZD","BRL":"BRL"}', 'crypto' => '0', 'extra' => null, 'description' => null, 'created_at' => null, 'updated_at' => '2024-10-14 00:19:38'],
            ['id' => '37', 'form_id' => '0', 'code' => '120', 'name' => 'Authorize.net', 'alias' => 'Authorize', 'image' => '66f92de1ce5151727606241.png', 'status' => '1', 'gateway_parameters' => '{"login_id":{"title":"Login ID","global":true,"value":"59e4P9DBcZv"},"transaction_key":{"title":"Transaction Key","global":true,"value":"47x47TJyLw2E7DbR"}}', 'supported_currencies' => '{"USD":"USD","CAD":"CAD","CHF":"CHF","DKK":"DKK","EUR":"EUR","GBP":"GBP","NOK":"NOK","PLN":"PLN","SEK":"SEK","AUD":"AUD","NZD":"NZD"}', 'crypto' => '0', 'extra' => null, 'description' => null, 'created_at' => null, 'updated_at' => '2024-10-03 03:12:33'],
            ['id' => '50', 'form_id' => '0', 'code' => '507', 'name' => 'BTCPay', 'alias' => 'BTCPay', 'image' => '66f92dab2d0c81727606187.png', 'status' => '1', 'gateway_parameters' => '{"store_id":{"title":"Store Id","global":true,"value":"GLeYKqo2vM1jW9e2aFpGsLqokwTbfpQ3yZFQBRy2um58"},"api_key":{"title":"Api Key","global":true,"value":"a60a2d61645cddd1f552212ca0f802121e47d08c"},"server_name":{"title":"Server Name","global":true,"value":"https:\\/\\/testnet.demo.btcpayserver.org"},"secret_code":{"title":"Secret Code","global":true,"value":"SUCdqPn9CDkY7RmJHfpQVHP2Lf2"}}', 'supported_currencies' => '{"BTC":"Bitcoin","LTC":"Litecoin"}', 'crypto' => '1', 'extra' => '{"webhook":{"title": "IPN URL","value":"ipn.BTCPay"}}', 'description' => null, 'created_at' => null, 'updated_at' => '2024-10-14 03:40:52'],
            ['id' => '51', 'form_id' => '0', 'code' => '508', 'name' => 'NowPayments - Hosted', 'alias' => 'NowPaymentsHosted', 'image' => '66f92ffed509e1727606782.png', 'status' => '1', 'gateway_parameters' => '{"api_key":{"title":"API Key","global":true,"value":"MAFWEB2-X6146ZP-KJTB98H-QV2WW46"},"secret_key":{"title":"Secret Key","global":true,"value":"yr2n6OSV5tvb9h0YdXy+2Fmihp4LwSnq"}}', 'supported_currencies' => '{"BTG":"BTG","ETH":"ETH","XMR":"XMR","ZEC":"ZEC","XVG":"XVG","ADA":"ADA","LTC":"LTC","BCH":"BCH","QTUM":"QTUM","DASH":"DASH","XLM":"XLM","XRP":"XRP","XEM":"XEM","DGB":"DGB","LSK":"LSK","DOGE":"DOGE","TRX":"TRX","KMD":"KMD","REP":"REP","BAT":"BAT","ARK":"ARK","WAVES":"WAVES","BNB":"BNB","XZC":"XZC","NANO":"NANO","TUSD":"TUSD","VET":"VET","ZEN":"ZEN","GRS":"GRS","FUN":"FUN","NEO":"NEO","GAS":"GAS","PAX":"PAX","USDC":"USDC","ONT":"ONT","XTZ":"XTZ","LINK":"LINK","RVN":"RVN","BNBMAINNET":"BNBMAINNET","ZIL":"ZIL","BCD":"BCD","USDT":"USDT","USDTERC20":"USDTERC20","CRO":"CRO","DAI":"DAI","HT":"HT","WABI":"WABI","BUSD":"BUSD","ALGO":"ALGO","USDTTRC20":"USDTTRC20","GT":"GT","STPT":"STPT","AVA":"AVA","SXP":"SXP","UNI":"UNI","OKB":"OKB","BTC":"BTC"}', 'crypto' => '1', 'extra' => '', 'description' => null, 'created_at' => null, 'updated_at' => '2024-10-13 02:56:13'],
            ['id' => '52', 'form_id' => '0', 'code' => '509', 'name' => 'NowPayments - Checkout', 'alias' => 'NowPaymentsCheckout', 'image' => '66f92ff5897b41727606773.png', 'status' => '1', 'gateway_parameters' => '{"api_key":{"title":"API Key","global":true,"value":"MAFWEB2-X6146ZP-KJTB98H-QV2WW46"},"secret_key":{"title":"Secret Key","global":true,"value":"yr2n6OSV5tvb9h0YdXy+2Fmihp4LwSnq"}}', 'supported_currencies' => '{"USD":"USD","EUR":"EUR"}', 'crypto' => '1', 'extra' => '', 'description' => null, 'created_at' => null, 'updated_at' => '2024-10-13 02:47:13'],
            ['id' => '53', 'form_id' => '0', 'code' => '122', 'name' => '2Checkout', 'alias' => 'TwoCheckout', 'image' => '66f93484853cf1727607940.png', 'status' => '1', 'gateway_parameters' => '{"merchant_code":{"title":"Merchant Code","global":true,"value":"255237318607"},"secret_key":{"title":"Secret Key","global":true,"value":"tNbET^O0mlJ4QHdAf6W#"}}', 'supported_currencies' => '{"AFN": "AFN","ALL": "ALL","DZD": "DZD","ARS": "ARS","AUD": "AUD","AZN": "AZN","BSD": "BSD","BDT": "BDT","BBD": "BBD","BZD": "BZD","BMD": "BMD","BOB": "BOB","BWP": "BWP","BRL": "BRL","GBP": "GBP","BND": "BND","BGN": "BGN","CAD": "CAD","CLP": "CLP","CNY": "CNY","COP": "COP","CRC": "CRC","HRK": "HRK","CZK": "CZK","DKK": "DKK","DOP": "DOP","XCD": "XCD","EGP": "EGP","EUR": "EUR","FJD": "FJD","GTQ": "GTQ","HKD": "HKD","HNL": "HNL","HUF": "HUF","INR": "INR","IDR": "IDR","ILS": "ILS","JMD": "JMD","JPY": "JPY","KZT": "KZT","KES": "KES","LAK": "LAK","MMK": "MMK","LBP": "LBP","LRD": "LRD","MOP": "MOP","MYR": "MYR","MVR": "MVR","MRO": "MRO","MUR": "MUR","MXN": "MXN","MAD": "MAD","NPR": "NPR","TWD": "TWD","NZD": "NZD","NIO": "NIO","NOK": "NOK","PKR": "PKR","PGK": "PGK","PEN": "PEN","PHP": "PHP","PLN": "PLN","QAR": "QAR","RON": "RON","RUB": "RUB","WST": "WST","SAR": "SAR","SCR": "SCR","SGD": "SGD","SBD": "SBD","ZAR": "ZAR","KRW": "KRW","LKR": "LKR","SEK": "SEK","CHF": "CHF","SYP": "SYP","THB": "THB","TOP": "TOP","TTD": "TTD","TRY": "TRY","UAH": "UAH","AED": "AED","USD": "USD","VUV": "VUV","VND": "VND","XOF": "XOF","YER": "YER"}', 'crypto' => '0', 'extra' => '{"approved_url":{"title": "Approved URL","value":"ipn.TwoCheckout"}}', 'description' => null, 'created_at' => null, 'updated_at' => '2024-10-13 05:40:07'],
            ['id' => '54', 'form_id' => '0', 'code' => '123', 'name' => 'Checkout', 'alias' => 'Checkout', 'image' => '66f92e6bd08e01727606379.png', 'status' => '0', 'gateway_parameters' => '{"secret_key":{"title":"Secret Key","global":true,"value":"------"},"public_key":{"title":"PUBLIC KEY","global":true,"value":"------"},"processing_channel_id":{"title":"PROCESSING CHANNEL","global":true,"value":"------"}}', 'supported_currencies' => '{"USD":"USD","EUR":"EUR","GBP":"GBP","HKD":"HKD","AUD":"AUD","CAN":"CAN","CHF":"CHF","SGD":"SGD","JPY":"JPY","NZD":"NZD"}', 'crypto' => '0', 'extra' => null, 'description' => null, 'created_at' => null, 'updated_at' => '2024-09-30 01:55:03'],
            ['id' => '55', 'form_id' => '19', 'code' => '1000', 'name' => 'Bank Transfer', 'alias' => 'bank_transfer', 'image' => '66f95525bfa571727616293.png', 'status' => '1', 'gateway_parameters' => '[]', 'supported_currencies' => '[]', 'crypto' => '0', 'extra' => null, 'description' => '<div style="border-left: 3px solid #b5b0b0;
    padding: 12px;
    font-style: italic;
    margin: 30px 0px;
    background: #f9f9f9;
    border-radius: 3px;"><p style="
    margin-bottom: 10px;
    font-weight: bold;
    font-size: 17px;
">Please send the funds to the information provided below. We cannot be held responsible for any errors if the amount is sent to incorrect details. Kindly complete the form after transferring the funds<br><br>Bank information</p><p style="
    margin-bottom: 0;
">
</p><p style="
margin-bottom: 0;
"><span style="font-weight:500">Bank Name:</span>&nbsp;Demo Bank</p>
<p style="
margin-bottom: 0;
"><span style="font-weight:500">Branch:</span>&nbsp;Demo Branch</p>
<p style="
margin-bottom: 0;
"><span style="font-weight:500">Routing:</span> 1234</p>
<p style="
    margin-bottom: 0;
"><span style="font-weight:500">Account Number:</span> xxx-xxx-<span style="color: rgb(67, 64, 79); font-weight: var(--bs-body-font-weight); text-align: var(--bs-body-text-align); display: inline !important;">xxx-xxx-xxx</span></p></div>', 'created_at' => '2024-03-13 23:11:21', 'updated_at' => '2024-10-05 03:08:54'],
            ['id' => '56', 'form_id' => '0', 'code' => '510', 'name' => 'Binance', 'alias' => 'Binance', 'image' => '66f92d4ae66161727606090.png', 'status' => '1', 'gateway_parameters' => '{"api_key":{"title":"API Key","global":true,"value":"--------------------"},"secret_key":{"title":"Secret Key","global":true,"value":"--------------------"},"merchant_id":{"title":"Merchant ID","global":true,"value":"-------------"}}', 'supported_currencies' => '{"BTC":"Bitcoin","USD":"USD","BNB":"BNB"}', 'crypto' => '1', 'extra' => '{"cron":{"title": "Cron Job URL","value":"ipn.Binance"}}', 'description' => null, 'created_at' => null, 'updated_at' => '2024-10-14 00:18:37'],
            ['id' => '57', 'form_id' => '0', 'code' => '124', 'name' => 'SslCommerz', 'alias' => 'SslCommerz', 'image' => '66f93471b7b9b1727607921.png', 'status' => '1', 'gateway_parameters' => '{"store_id":{"title":"Store ID","global":true,"value":"---------"},"store_password":{"title":"Store Password","global":true,"value":"----------"}}', 'supported_currencies' => '{"BDT":"BDT","USD":"USD","EUR":"EUR","SGD":"SGD","INR":"INR","MYR":"MYR"}', 'crypto' => '0', 'extra' => null, 'description' => null, 'created_at' => null, 'updated_at' => '2024-09-29 05:05:21'],
            ['id' => '58', 'form_id' => '0', 'code' => '125', 'name' => 'Aamarpay', 'alias' => 'Aamarpay', 'image' => '66f933390c5201727607609.png', 'status' => '0', 'gateway_parameters' => '{"store_id":{"title":"Store ID","global":true,"value":"---------"},"signature_key":{"title":"Signature Key","global":true,"value":"----------"}}', 'supported_currencies' => '{"BDT":"BDT"}', 'crypto' => '0', 'extra' => null, 'description' => null, 'created_at' => null, 'updated_at' => '2024-10-14 06:00:24'],
            ['id' => '60', 'form_id' => '22', 'code' => '1001', 'name' => 'Mobile Money Transfer', 'alias' => 'mobile_money_transfer', 'image' => '670e115c4d5251728975196.png', 'status' => '1', 'gateway_parameters' => '[]', 'supported_currencies' => '[]', 'crypto' => '0', 'extra' => null, 'description' => '<p style="margin-bottom: 10px; font-size: 17px; font-weight: bold; font-style: italic;">Please send the funds to the information provided below. We cannot be held responsible for any errors if the amount is sent to incorrect details. Kindly complete the form after transferring the funds<br><br>Bank information</p><p style="font-style: italic;"></p><p style="font-style: italic;"><span style="color: hsl(var(--body-color)); font-size: 0.875rem; background-color: hsl(var(--white)); text-align: var(--bs-body-text-align); display: inline !important;">Mobile Number:&nbsp;xxx-xxx-</span><span style="font-size: 0.875rem; font-weight: var(--bs-body-font-weight); background-color: hsl(var(--white)); text-align: var(--bs-body-text-align); color: rgb(67, 64, 79); display: inline !important;">xxx-xxx-xxx</span><br></p>', 'created_at' => '2024-09-25 08:22:40', 'updated_at' => '2024-10-15 00:53:33'],
        ]);
    }
}
